version: '3.10'
services:
  database:
    container_name: Silicium-test-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: